version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-service:
    build: ./main-service
    ports:
      - "8080:8080"
    depends_on:
      - event-keeper-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://event-keeper-db:5432/events
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_STATSSERVICE_URL=http://stats-server:9090

  event-keeper-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=events
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

